### ISSUE TITLE
Run playwright on lambda with node

### ISSUE THREAD

**Issue by sch-collab** [george-lim/firefox-lambda#1]
FROM public.ecr.aws/george-lim/firefox-lambda:1.0.1 as firefox

FROM public.ecr.aws/lambda/nodejs:12

COPY --from=firefox /opt/firefox /opt/firefox

RUN yum install -y \
    dbus-glib-0.100-7.2.amzn2 \
    gtk3-3.22.30-3.amzn2 \
    libXt-1.1.5-3.amzn2.0.2 \
  && yum clean all

COPY app.js package*.json ./

RUN npm install

ENV FIREFOX_BINARY_PATH=/opt/firefox/firefox

CMD [ "app.lambdaHandler" ]

I have built docker with above file and deployed lambda with this container.
But I have failed. Following is the lambda logs.

```<launching> /opt/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-BYvMgD -juggler-pipe -silent
<launched> pid=23
[err] *** You are running in headless mode.
[err] ExceptionHandler::GenerateDump cloned child 34
[err] ExceptionHandler::SendContinueSignalToChild sent continue signal to child
[err] ExceptionHandler::WaitForContinueSignal waiting for continue signal...
=========================== logs ===========================
<launching> /opt/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-BYvMgD -juggler-pipe -silent
<launched> pid=23
[err] *** You are running in headless mode.
[err] ExceptionHandler::GenerateDump cloned child 34
[err] ExceptionHandler::SendContinueSignalToChild sent continue signal to child
[err] ExceptionHandler::WaitForContinueSignal waiting for continue signal...
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
    at Connection.sendMessageToServer (/var/task/node_modules/playwright/lib/client/connection.js:69:15)
    at Proxy.<anonymous> (/var/task/node_modules/playwright/lib/client/channelOwner.js:44:61)
    at /var/task/node_modules/playwright/lib/client/browserType.js:61:73
    at BrowserType._wrapApiCall (/var/task/node_modules/playwright/lib/client/channelOwner.js:72:34)
    at BrowserType.launch (/var/task/node_modules/playwright/lib/client/browserType.js:52:21)
    at Runtime.exports.lambdaHandler [as handler] (/var/task/app1.js:6:39)
    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)
END RequestId: ec405a11-a666-42ff-a6e3-a87050e38716
REPORT RequestId: ec405a11-a666-42ff-a6e3-a87050e38716	Duration: 1636.06 ms	Billed Duration: 2771 ms	Memory Size: 512 MB	Max Memory Used: 166 MB	Init Duration: 1134.78 ms	```

What should I do for this?

**Comment by george-lim** [comment]
Hi there,

There is currently an unknown bug on AWS’s side that always causes the headless browser to crash while Playwright is initializing. While I am unable to solve the problem, I did find out that it was caused by Lambda killing threads started in Lambda Container Images that aren't related to your main process. In this case, Lambda is killing the thread that is required to start the browser.

I only found this out after developing firefox-lambda. Firefox-lambda was working on my local machine and - it being a Docker image, I assumed that it would work in any environment. This does not appear to be the case.
 
Just to confirm: it isn't my docker image that is buggy. I did some research online and found that other people have apparently been experiencing this problem for months, ever since Lambda container images came out. It appears this is a pretty big use case of Lambda container images.  

Here are some links to other people who have experienced this problem:
https://stackoverflow.com/questions/63570435/how-to-create-a-lambda-layer-with-selenium-3-and-firefox
https://dockerquestions.com/2020/12/23/aws-lambda-container-running-selenium-with-headless-chrome-works-locally-but-not-in-aws-lambda/
https://stackoverflow.com/questions/65385952/why-is-my-containerized-selenium-application-failing-only-in-aws-lambda
